import { Subscription } from 'rxjs'
import { environment } from 'src/environments/environment'

export const genralConfig = {
ticket_config: {

    projectId: "651fdbba94ecdb4a29d37094",

  }, 
 GPSCONFIG: {
    // API_KEY: 'zc9hdsTH7XOx170MeAyMSWU0MBXLGhrH',
    API_KEY: 'FAwecAoL8qcVNzRyX18RPYKkcfrGTvdB',
    // WeatherApiKey : '85e6f810f400417f90655158212511',
    WeatherApiKey: '2ce76fc3d0f2418eb33221421222104',
    openWeather: 'ac28144128e3e4ab587cb71010a57208',
  },
  messages: {
    apiError: 'Something went wrong!',
    startDate: 'Please select start Date',
    formInvalid: 'Please enter mandatory fields',
    imageFormat: 'Only jpeg, png file format are allowed',
    deleteMessage: 'Are you sure you want to delete this information?',
  },

  chatEndPoints: {
    // chatNameSpace: '/chat',
    connect: 'connection',
    sendMsg: 'send-message',
    receiveMsg: 'receive-message',
    joinConversation: 'join-conversation',
    leaveConversation: 'leave-conversation',
    joinNewConversation: 'join-new-conversation',
    newConversationStart: 'new-conversation-started',
  },
  chatCodes: {
    success: 200,
    isNotMember: 402,
    isAdminOnly: 403,
    isBlocked: 404,
  },
  chatTypes: {
    GRP: 'GROUP',
    IND: 'INDIVIDUAL',
    SEL: 'SELLER',
  },
  serverImageUrl: {
    profile: '/upload/profiles/thumbnail/',
  },

  networkImages: {
    network_image: environment.URLHOST + '/uploads/post/image/',
    network_video: environment.URLHOST + '/uploads/post/video/',
  },
  commentCount: 5,
  storage: {
    USER: 'user',
    USERNAME: 'username',
    USERTYPE: 'usertype',
    PROFILE_PIC: 'profilepic',
    TOKEN: 'token',
    ID: 'id',
    USERFNAME: 'userfname',
    USERLNAME: 'userlname',
    All: 'all',
    PERMISSION: 'PERMISSION',
    COMPANYFROMFIELDS: 14,
    USERFROMFIELDS: 14,
    SELLERFROMFIELDS: 12,
  },

  pattern: {
    // 'NAME': /^[a-zA-Z,.'\-\,]+$/,
    // "CITY": /^[a-zA-Z . \-\']*$/,
    // "POSTAL_CODE": /^[0-9A-Z]{4}/, // /^\d{5}-\d{4}|\d{5}|[A-Z]\d[A-Z] \d[A-Z]\d$/,
    // "PHONE_NO": /^\(?(?:\+?61|0)(?:(?:2\)?[ -]?(?:3[ -]?[38]|[46-9][ -]?[0-9]|5[ -]?[0-35-9])|3\)?(?:4[ -]?[0-57-9]|[57-9][ -]?[0-9]|6[ -]?[1-67])|7\)?[ -]?(?:[2-4][ -]?[0-9]|5[ -]?[2-7]|7[ -]?6)|8\)?[ -]?(?:5[ -]?[1-4]|6[ -]?[0-8]|[7-9][ -]?[0-9]))(?:[ -]?[0-9]){6}|4\)?[ -]?(?:(?:[01][ -]?[0-9]|2[ -]?[0-57-9]|3[ -]?[1-9]|4[ -]?[7-9]|5[ -]?[018])[ -]?[0-9]|3[ -]?0[ -]?[0-5])(?:[ -]?[0-9]){5})$/,
    // "MOB_NO": /^\(?(?:\+?61|0)(?:(?:2\)?[ -]?(?:3[ -]?[38]|[46-9][ -]?[0-9]|5[ -]?[0-35-9])|3\)?(?:4[ -]?[0-57-9]|[57-9][ -]?[0-9]|6[ -]?[1-67])|7\)?[ -]?(?:[2-4][ -]?[0-9]|5[ -]?[2-7]|7[ -]?6)|8\)?[ -]?(?:5[ -]?[1-4]|6[ -]?[0-8]|[7-9][ -]?[0-9]))(?:[ -]?[0-9]){6}|4\)?[ -]?(?:(?:[01][ -]?[0-9]|2[ -]?[0-57-9]|3[ -]?[1-9]|4[ -]?[7-9]|5[ -]?[018])[ -]?[0-9]|3[ -]?0[ -]?[0-5])(?:[ -]?[0-9]){5})$/,

    /* "PHONE_NO" : /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/  - for 10-12 valid digits */

    NAME: /^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$/,
    NAMENumber: /^[a-zA-Z0-9]+(([',. -][a-zA-Z0-9 ])?[a-zA-Z0-9]*)*$/,
    CLAIMNUMBER: /^[ A-Za-z0-9]*$/,
    REPORTNAME: /^[ A-Za-z]*$/,
    CODE: /^[ A-Za-z_@./#&+-/'/"]*$/,
    DURATION: /^[0-9]{0,3}$/,
    PRICING: /^[0-9.]{0,30}$/,
    CITY: /^([a-zA-Z\u0080-\u024F]+(?:. |-| |'))*[a-zA-Z\u0080-\u024F]*$/,
    EMAIL: /^(([^<>()\[\]\\.,,:\s@"]+(\.[^<>()\[\]\\.,,:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    POSTAL_CODE: /^\d{5}-\d{4}|\d{4}|[A-Z]\d[A-Z] \d[A-Z]\d$/,
    PHONE_NO: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,4}$/,
    FIRM_NUMBER: /^[a-z0-9\-]+$/,
    ALPHANUM: /^[a-zA-Z0-9]+$/,
    MOB_NO: /\(?\d{3}\)?-? *\d{3}-? *-?\d{4}/,
    PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$#!%*?&])[A-Za-z\d$@#$!%*?&]{6,}/,
    DESCRIPTION: /^[ !@#$%^&*()~:;{}?'"=<>A-Za-z0-9_@./#&+-,-]*$/,
    REFNO: /^[ 0-9_@./#&+-,-]*$/,
    TASK_CODE: /^[0-9999]{1,4}$/,
    SUB_DOMAIN: /^[/a-z/A-Z][a-zA-Z0-9-]*[^/-/./0-9]$/,
    PHONE_NO_MASK: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
    IVR_ACTION_KEY: /^[0-9]*$/,
    IVR_NUMBER: /^[1-9]*$/,
    RADIUS: /^[0-9]*(?:.)([0-9])+$/,
    LATLONG: /^\s*(\-?\d+(\.\d+)?)$/,
    SSN: /^((\d{3}-?\d{2}-?\d{4})|(X{3}-?X{2}-?X{4}))$/,
    SSN_MASK: [/\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
    PRACTICE_PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{6,})/,
    USERNAME: /^[a-zA-Z0-9](_(?!(\.|_))|\.(?!(_|\.))|[a-zA-Z0-9]){1,14}[a-zA-Z0-9]$/,
    USERNAME_MIN_SIZ: /^[a-zA-Z0-9_](_(?!(\.|_))|\.(?!(_|\.))|[a-zA-Z0-9_]){4,18}[a-zA-Z0-9_]$/,
    WICARE_USERNAME: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{1,}/,
    YEAR_MASK: /d{4}/,
    PRODUCTVIN_MIN_SIZ: /^[a-zA-Z0-9_](_(?!(\.|_))|\.(?!(_|\.))|[a-zA-Z0-9_]){1,17}[a-zA-Z0-9_]$/,
    PRODUCTIVE_MAX_SIZ: /^[a-zA-Z0-9]{17,}$/,
    PRODUCTMILEAGEMIN_SIZ: /^[0-9](?![\s-])[\w\s-]+$/,
    PRODUCTPRICE_SIZ: /^[1-9.]{0,30}(?![\s-])[\w\s-]+$/,
    PRODUCTLENGTH_SIZ: /^[1-9.]{0,30}(?![\s-,s+])[\w]+$/,
    DECIMAL: /\d+(\.\d{1,2})?/,
    NUMBERnDECIMAL: '^\\d+(\\.\\d+)?$',
    WHITESPACE: /^(?![\s-])[\w\s-]+$/,
    FIRSTSPACE: /^(?=\S+)(?=[a-zA-ZàáâäãåèéêëìíîïòóôöõøùúûüÿýñçčšžÀÁÂÄÃÅÈÉÊËÌÍÎÏÒÓÔÖÕØÙÚÛÜŸÝÑßÇŒÆČŠŽ∂ð ,.'-]*$).*(?=\S).$/,
    MAXLENGTH: /^.{1,10226}$/,
    MINLENGTH: 3,
    PASSWORDMINLENGTH: 6,
    PASSWORDMAXLENGTH: 15,
    MINIMUMVACANCY: 1,
    MAXIMUMVACANCY: 2,
    BACKSPACE: /^((?!\s{2,}).)*$/,
    // BACKSPACE:.*\\S.*[a-zA-z0-9 ],
    URL:
      '^(https?:\\/\\/)?' + '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' + '((\\d{1,3}\\.){3}\\d{1,3}))' + '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + '(\\?[;&a-z\\d%_.~+=-]*)?' + '(\\#[-a-z\\d_]*)?$',
  },

  eventPaginator: {
    COUNT: 4,
    PAGE: 1,
  },
  enevtPageNationConfig: {
    itemsPerPage: 4,
    currentPage: 1,
  },
  paginator: {
    COUNT: 10,
    PAGE: 1,
  },
  workingHours: [{ wh: 'Hourly' }, { wh: 'Annually' }],

  pageNationConfig: {
    itemsPerPage: 10,
    currentPage: 1,
  },
  
  chatlink: {
    // generatelinkPort: "http://localhost:4200",
    // generatelinkPort: "http://localhost:4200",
//    generatelinkPort: "https://mytruck.one",
generatelinkPort: "https://zimotechnologies.in:30001",
  },
  rolename: {
    COMPANY: 'COMPANY',
    DRIVER: 'DRIVER',
    ATTENDEE: 'ATTENDEE',
    JOBSEEKER: 'JOBSEEKER',
    USER: 'USER',
    ENDUSER: 'ENDUSER',
    SELLER: 'SELLER',
    HR: 'HR',
  },

  statusCode: {
    ok: 200,
    unauth: 401,
    warning: 404,
    validation: 400,
    failed: 1002,
    invalidURL: 1001,
    paymentReq: 402,
    internalError: 1004,
    forbidden: 403,
    internalservererror: 500,
    alreadyExist: 409, //conflict
    Completed: 'Completed',
    Cancelled: 'Cancelled',
  },

  gender: [{ gender: 'Male' }, { gender: 'Female' }, { gender: 'Others' }],

  maritalStatus: [{ maritalStatus: 'Married' }, { maritalStatus: 'Single' },{ maritalStatus: 'Others' } ],

  minexperience: [
    { minexperience: 0 },
    { minexperience: 1 },
    { minexperience: 2 },
    { minexperience: 3 },
    { minexperience: 4 },
    { minexperience: 5 },
    { minexperience: 6 },
    { minexperience: 7 },
    { minexperience: 8 },
    { minexperience: 9 },
    { minexperience: 10 },
    { minexperience: 11 },
    { minexperience: 12 },
    { minexperience: 13 },
    { minexperience: 14 },
  ],

  experience: [
    { experience: 0 },
    { experience: 1 },
    { experience: 2 },
    { experience: 3 },
    { experience: 4 },
    { experience: 5 },
    { experience: 6 },
    { experience: 7 },
    { experience: 8 },
    { experience: 9 },
    { experience: 10 },
    { experience: 11 },
    { experience: 12 },
    { experience: 13 },
    { experience: 14 },
    { experience: 15 },
  ],

  maxexperience: [
    { maxexperience: 1 },
    { maxexperience: 2 },
    { maxexperience: 3 },
    { maxexperience: 4 },
    { maxexperience: 5 },
    { maxexperience: 6 },
    { maxexperience: 7 },
    { maxexperience: 8 },
    { maxexperience: 9 },
    { maxexperience: 10 },
    { maxexperience: 11 },
    { maxexperience: 12 },
    { maxexperience: 13 },
    { maxexperience: 14 },
    { maxexperience: 15 },
  ],

  minsalary: [
    { minsalary: '0' },
    { minsalary: '50000' },
    { minsalary: '100000' },
    { minsalary: '200000' },
    { minsalary: '300000' },
    { minsalary: '400000' },
    { minsalary: '500000' },
    { minsalary: '600000' },
    { minsalary: '700000' },
    { minsalary: '800000' },
    { minsalary: '900000' },
    { minsalary: '1000000' },
    { minsalary: '2000000' },
    { minsalary: '3000000' },
  ],

  maxsalary: [
    { maxsalary: '100000' },
    { maxsalary: '200000' },
    { maxsalary: '300000' },
    { maxsalary: '400000' },
    { maxsalary: '500000' },
    { maxsalary: '600000' },
    { maxsalary: '700000' },
    { maxsalary: '800000' },
    { maxsalary: '900000' },
    { maxsalary: '1000000' },
    { maxsalary: '2000000' },
    { maxsalary: '3000000' },
    { maxsalary: '4000000' },
  ],

  employees: [
    { employees: 'Full Time, Permanent' },
    { employees: 'Full Time, Temporary/Contractual' },
    { employees: 'Full Time, Freelance/Homebased' },
    { employees: 'Part Time, Permanent' },
    { employees: 'Part Time, Temporary/Contractual' },
    { employees: 'Part Time, Freelance/Homebased' },
  ],
  typeList: [{ name: 'Lease' }, { name: 'Rent' }, { name: 'Sale' }],
  transmissionType: [{ name: 'Automatic' }, { name: 'Manual' }],
  wheelType: [{ name: 'Aluminium' }, { name: 'Steel' }],
  fuelType: [{ name: 'Diesel' }, { name: 'Petrol' }],
  breaksList: [{ name: 'Air' }, { name: 'Disc' }],
  suspensionList: [{ name: 'Air' }, { name: 'Spring' }],
  inStockList: [{ name: 'No' }, { name: 'Yes' }],
  colorList: [
    { name: 'Black', colorCode: '#000' },
    { name: 'Green', colorCode: '#34a853' },
    { name: 'Red', colorCode: '#ff0000' },
    { name: 'White', colorCode: '#ffffff' },
  ],
  eventTypesList: [{ Type: 'Public' }, { Type: 'Private' }],
  Images: {
    eventBanner: '/uploads/event/image/',
    eventLogo: '/uploads/event/brand_logo/',
  },

  conditionList: [{ name: 'New' }, { name: 'Used' }],
  language: [
    { language: 'Arabic' },
    { language: 'Bengali' },
    { language: 'Chinese' },
    { language: 'Dutch' },
    { language: 'Danish' },
    { language: 'English' },
    { language: 'French' },
    { language: 'German' },
    { language: 'Gujarati' },
    { language: 'Hindi' },
    { language: 'Indonesian' },
    { language: 'Italian' },
    { language: 'Japanese' },
    { language: 'Korean' },
    { language: 'Kannada' },
    { language: 'Marathi' },
    { language: 'Punjabi' },
    { language: 'Portuguese' },
    { language: 'Russian' },
    { language: 'Spanish' },
    { language: 'Tamil' },
    { language: 'Telugu' },
    { language: 'Turkish' },
    { language: 'Urdu' },

  ],
  defaultLanguage: [
    { language: 'English', code: 'en' },
    { language: 'Punjabi', code: 'pa' },
    { language: 'Spanish', code: 'es' },
  ],

  designation: [{ designation: 'Driver' }, { designation: 'Supervisor' }, { designation: 'Conductor' }],

  religion: [{ religion: 'Hinduism' }, { religion: 'Islam' }, { religion: 'Sikhism' }, { religion: 'Jainism' }, { religion: 'Buddhism' }, { religion: 'Christianity' }],

  loadType: [
    { type: 'Explosives', class: 'USHazmatClass1' },
    { type: 'Compressed gas', class: 'USHazmatClass2' },
    { type: 'Flammable liquids', class: 'USHazmatClass3' },
    { type: 'Flammable solids', class: 'USHazmatClass4' },
    { type: 'Oxidizers', class: 'USHazmatClass5' },
    { type: 'Poisons', class: 'USHazmatClass6' },
    { type: 'Radioactive', class: 'USHazmatClass7' },
    { type: 'Corrosives', class: 'USHazmatClass8' },
    { type: 'Miscellaneous', class: 'USHazmatClass9' },
  ],
  services: [
    { services: 'Agriculture & Forestry/Wildlife' },
    { services: 'Business & Information' },
    { services: 'Construction/Utilities/Contracting' },
    { services: 'Education' },
    { services: 'Finance & Insurance' },
    { services: 'Food & Hospitality' },
    { services: 'Gaming' },
    { services: 'Health services' },
    { services: 'Motor Vehicle' },
    { services: 'Natural Resources/Environmental' },
    { services: 'Personal services' },
    { services: 'Real Estate & Housing' },
    { services: 'Safety/Security & Legal' },
    { services: 'Transportation' },
  ],
  mapServices: [
    { serviceName: 'Truck Wash', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/truckWashing.png' },
    { serviceName: 'Truck Repair', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/truckRepair.png' },
    { serviceName: 'Trailer Repair', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/trailerRepair.png' },
    { serviceName: 'Parking', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/truckParking.png' },
    { serviceName: 'Rest Area', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/restArea.png' },
    { serviceName: 'Fuel Station', serviceIcon: environment.URLHOST + '/uploads/serviceIcons' + '/gaspump.png' },
  ],

  maneuver: [
    {
      ARRIVE: '/assets/Directions/arrive.svg',
      ARRIVE_RIGHT: '/assets/Directions/arrive.svg',
      ARRIVE_LEFT: '/assets/Directions/arrive.svg',
      DEPART: '/assets/Directions/leave.svg',
      STRAIGHT: '/assets/Directions/follow-arrow.svg',
      KEEP_RIGHT: '/assets/Directions/turn-right.svg',
      BEAR_RIGHT: '/assets/Directions/right.svg',
      TURN_RIGHT: '/assets/Directions/turn-right.svg',
      SHARP_RIGHT: '/assets/Directions/turn-right.svg',
      KEEP_LEFT: '/assets/Directions/turn-left.svg',
      BEAR_LEFT: '/assets/Directions/right-arrow.svg',
      TURN_LEFT: '/assets/Directions/turn-left.svg',
      SHARP_LEFT: '/assets/Directions/turn-left.svg',
      MAKE_UTURN: '/assets/Directions/u-turn.png',
      ENTER_MOTORWAY: '/assets/Directions/motorWay.svg',
      ENTER_FREEWAY: '/assets/Directions/motorWay.svg',
      ENTER_HIGHWAY: '/assets/Directions/motorWay.svg',
      TAKE_EXIT: '/assets/Directions/follow-arrow.svg',
      MOTORWAY_EXIT_RIGHT: '/assets/Directions/right.svg',
      MOTORWAY_EXIT_LEFT: '/assets/Directions/right-arrow.svg',
      TAKE_FERRY: '/assets/Directions/ferry.png',
      ROUNDABOUT_CROSS: '/assets/Directions/roundAboutLeft1.svg',
      ROUNDABOUT_LEFT: '/assets/Directions/roundAboutLeft.svg',
      ROUNDABOUT_RIGHT: '/assets/Directions/roundAboutRight.svg',
      ROUNDABOUT_BACK: '/assets/Directions/roundAboutBack.png',
      TRY_MAKE_UTURN: '/assets/Directions/u-turn.png',
      FOLLOW: '/assets/Directions/follow-arrow.svg',
      SWITCH_PARALLEL_ROAD: '/assets/Directions/switchParallelRoad.png',
      SWITCH_MAIN_ROAD: '/assets/Directions/switchToMainRoad.png',
      ENTRANCE_RAMP: '/assets/Directions/ramp.png',
      WAYPOINT_LEFT: '/assets/Directions/right-arrow.svg',
      WAYPOINT_RIGHT: '/assets/Directions/right.svg',
      WAYPOINT_REACHED: '/assets/Directions/wayPointReached.png',
    },
  ],
  currency: [{ currency: 'USD' }, { currency: 'CAD' }, { currency: 'MXN' }],

  document_extension_array: ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
  chatDocumentExtension: ['application/pdf', 'image/jpeg', 'image/png'],

  passwordCreatedmessage: 'Password created sucessfully',
  Interested: 'Interested',
  statusList: [
    { value: 'true', name: 'Active' },
    { value: 'false', name: 'In-active' },
  ],
  deleteArray: [
    { value: 'true', name: 'Archived' },
    { value: 'false', name: 'Unarchived' },
  ],

  subscriptionPlan: {
    planExpireIn: 7,
  },

}
